//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaiWebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.T_livro = new HashSet<Livro>();
        }
    
        public int Id_categoria { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Livro> T_livro { get; set; }
    }
}
