//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaiWebRole.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityDai : DbContext
    {
        public EntityDai()
            : base("name=EntityDai")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Foto> Fotos { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<Galeria> Galerias { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Emprestimo> Emprestimos { get; set; }
        public virtual DbSet<Livro> Livros { get; set; }
        public virtual DbSet<Membro> Membros { get; set; }
        public virtual DbSet<Utilizador> Utilizadores { get; set; }
    }
}
