//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaiWebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galeria
    {
        public int Id { get; set; }
        public int Foto { get; set; }
        public int Video { get; set; }
    
        public virtual Foto Foto1 { get; set; }
        public virtual Video Video1 { get; set; }
    }
}
