//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaiWebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro
    {
        public Livro()
        {
            this.T_emprestimo = new HashSet<Emprestimo>();
        }
    
        public int Id_livro { get; set; }
        public string Titulo_livro { get; set; }
        public string Capa_livro { get; set; }
        public int Categoria_Id { get; set; }
        public string Autor_livro { get; set; }
        public string Editora_livro { get; set; }
        public string Isbn { get; set; }
    
        public virtual Categoria T_categoria { get; set; }
        public virtual ICollection<Emprestimo> T_emprestimo { get; set; }
    }
}
