//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaiWebRole.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Membro
    {
        public Membro()
        {
            this.T_emprestimo = new HashSet<Emprestimo>();
        }
    
        public int Id_membro { get; set; }
        [Display(Name="Primeiro nome")]
        public string PrimeirNome { get; set; }
        [Display(Name = "Último nome")]
        public string UltimoNome { get; set; }
        [Display(Name = "Fotografia")]
        public string foto { get; set; }
        [Display(Name = "Género")]
        public string Genero { get; set; }
        [Display(Name = "Endereço")]
        public string Endereco { get; set; }
        [Display(Name = "Contacto")]
        public string Contacto { get; set; }
    
        public virtual ICollection<Emprestimo> T_emprestimo { get; set; }
    }
}
