//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaiWebRole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public Video()
        {
            this.Galerias = new HashSet<Galeria>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Galeria> Galerias { get; set; }
    }
}
